org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
fabric.loom.disableMinecraftVerification=true
axolotlclient.modules.all=true

version=1.0.0-beta
maven_group=io.github.itzclient
archives_base_name=ItzClient

minecraft_121=1.21.1
mappings_121=1.21.1+build.9
fabric_loader=0.17.0
fapi_121=0.116.6
config=3.0.17